# Generated by Django 4.1.10 on 2023-08-07 08:33

import base.common.constant.db_table
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (base.common.constant.app_label.ModelAppLabel["ADDRESS"], "0001_initial"),
        (base.common.constant.app_label.ModelAppLabel["MASTER"], "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(max_length=12, null=True, unique=True),
                ),
                ("first_name", models.CharField(max_length=32, null=True)),
                ("last_name", models.CharField(max_length=32, null=True)),
                ("dob", models.DateField(null=True)),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name=base.common.constant.db_table.DBTable["PROFILE"],
                        to="address.address",
                    ),
                ),
                (
                    "sex",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name=base.common.constant.db_table.DBTable["PROFILE"],
                        to="master.mastersex",
                    ),
                ),
            ],
            options={
                "db_table": base.common.constant.db_table.DBTable["PROFILE"],
            },
        ),
    ]
