# Generated by Django 4.1.10 on 2023-08-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="citizen_number",
            field=models.CharField(default=123456789012, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
